export const APP_NAME = "RestroZapp POS";
export const APP_VERSION = "1.0.0";
export const SUPABASE_FUNCTIONS_URL =
  "https://flrbzrgjsdrwbutkqxsp.supabase.co/functions/v1";
export const WINDOWS_DATA_DIR_NAME = "RestroZapp";
export const SUPABASE_PROJECT_REF = "flrbzrgjsdrwbutkqxsp";

export const BACKUP_RETENTION = {
  local: {
    daily: 7,
    weekly: 4,
    monthly: 6,
  },
  cloud: {
    weekly: 4,
    monthly: 6,
    manual: 3,
  },
} as const;

export const IPC_CHANNELS = {
  activationGetState: "activation:get-state",
  activationRequest: "activation:request",
  activationRefresh: "activation:refresh",
  systemStatus: "system:status",
  backupCreateNow: "backup:create-now",
  backupListLogs: "backup:list-logs",
  backupRestore: "backup:restore",
  backupListCloud: "backup:list-cloud",
  backupPullCloud: "backup:pull-cloud",
  syncStatus: "sync:status",
  syncNow: "sync:now",
  printQuick: "print:quick",
  printPdf: "print:pdf",
  printQueueStatus: "print:queue-status",
  printEnqueue: "print:enqueue",
  printEnqueueHtml: "print:enqueue-html",
  printRetryJob: "print:retry-job",
  printRetryFailed: "print:retry-failed",
  printQueueChanged: "print:queue-changed",
  updateCheck: "update:check",
  posBootstrap: "pos:bootstrap",
  posGetCatalog: "pos:get-catalog",
  posGetDashboard: "pos:get-dashboard",
  posListOrders: "pos:list-orders",
  posCreateOrder: "pos:create-order",
  posUpdateOrderStatus: "pos:update-order-status",
  posUpdateOrderItems: "pos:update-order-items",
  posCompleteOrder: "pos:complete-order",
  posToggleMenuItemPin: "pos:toggle-menu-item-pin",
  posSearchCustomers: "pos:search-customers",
  posGlobalSearch: "pos:global-search",
  posGetSettings: "pos:get-settings",
  posSetSetting: "pos:set-setting",
  posUpdateSettings: "pos:update-settings",
  posSaveRestaurantLogo: "pos:save-restaurant-logo",
  settingsChanged: "settings:changed",
  posVerifyPassword: "pos:verify-password",
  posChangePassword: "pos:change-password",
  printListPrinters: "print:list-printers",
  printTest: "print:test",
  inventoryGetCatalog: "inventory:get-catalog",
  inventoryCreateMenuItem: "inventory:create-menu-item",
  inventoryUpdateMenuItem: "inventory:update-menu-item",
  inventoryDeleteMenuItem: "inventory:delete-menu-item",
  inventoryToggleMenuItem: "inventory:toggle-menu-item",
  imageLibraryList: "image-library:list",
  imageLibraryStatus: "image-library:status",
  imageLibraryDownload: "image-library:download",
  imageLibraryRetry: "image-library:retry",
  imageLibraryChanged: "image-library:changed",
  inventoryBulkCategories: "inventory:bulk-categories",
  inventoryDeleteCategory: "inventory:delete-category",
  inventoryCreateKitchen: "inventory:create-kitchen",
  inventoryUpdateKitchen: "inventory:update-kitchen",
  inventoryDeleteKitchen: "inventory:delete-kitchen",
  inventoryToggleKitchen: "inventory:toggle-kitchen",
  customersList: "customers:list",
  customersCreate: "customers:create",
  customersUpdate: "customers:update",
  customersDelete: "customers:delete",
  groceryGetStore: "grocery:get-store",
  grocerySetStore: "grocery:set-store",
  dataExportCsv: "data:export-csv",
  reportExportPdf: "report:export-pdf",
} as const;
